[package]
name = "vkmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.34.1"
vulkano-shaders = { version = "0.34.0", features = [
    "shaderc-build-from-source",
] }
winit = "0.28.0"
